server:
  port: 9005
#自定义属性
name: andy
profile: test
level: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
      name: spring-cloud-config-server-bus
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fooelliot/config-repo.git
          basedir: D:\tmp\config
  rabbitmq:
    host: localhost
    port: 5672
    username: cloud
    password: cloud
    virtual-host: /cloud

management:
  endpoints:
    web:
      exposure:
        include: "*"
