spring:
  application:
    name: spring-cloud-eureka
  output:
    ansi:
      enabled: detect
  security:
    user:
      name: user
      password: password
server:
  port: 8761

#security:
#  basic:
#    enabled: true
#  user:
#    name: user              # 用户名
#    password: password123   # 用户密码

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
  dashboard:    #首页是否课可以访问
    enabled: true
  instance:
#    path: /x
management:
  endpoints:
    web:
      exposure:
        include: "*"
#datacenter: cloud
#environment: product

---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/


---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/