server:
  port: 8109

spring:
  application:
    name: spring-cloud-feign-hystrix
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#新版本中需要独立设置开启feign对hystrix的支持，旧版本中默认开启对hystrix支持
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
#      base-path: /