server:
  port: 9000

security:
  basic:
    enabled: true
  user:
    name: user              # 用户名
    password: password123    # 用户密码
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/thethink/config_repo