spring: 
  application:
    name: springCloud-provider-ribbon-hystrix
    
server:
  port: 8108

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
