server:
  port: 9100

spring:
  application:
    name: springcloud-config-client-eureka
  cloud:
    config:
      discovery:
        enabled: true
        service-id: springCloud-config-server-eureka

profile: abc
sql: oracle

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka