spring: 
  application:
    name: spring-cloud-order-ribbon
    
server:
  port: 8102
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: ORDER-CONSUMER-RIBBON
#    prefer-ip-address: true

#脱离eureka使用
ribbon:
  eureka:
   enabled: false

spring-cloud-provider:
  ribbon:
    listOfService: http://localhost:8001

#配置负载均衡的规则
spring-cloud-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule



