server:
  port: 9100

#自定义属性
sql: mysql
profile: abc


spring:
  application:
    name: aaaa
  cloud:
    config:
      uri: http://user:password123@localhost:9000/
      profile: test
      label: master
      username: user
      password: password1232

