spring: 
  application:
    name: springCloud-consumer-ribbon
    
server:
  port: 8102
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    appname: MOVIE-CONSUMER-RIBBON
#    prefer-ip-address: true
springCloud-provider.ribbon.listOfService: http://localhost:8001/