spring: 
  application:
    name: spring-cloud-consumer-ribbon
    
server:
  port: 8102
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: ORDER-CONSUMER-RIBBON
#    prefer-ip-address: true
spring-cloud-provider:
  ribbon.listOfService: http://localhost:8001/