server:
  port: 8105
spring:
  application:
    name: spring-cloud-order-config

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: order-config