server:
  port: 8105
spring:
  application:
    name: spring-cloud-consumer-feign

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: consumer-feign