server:
  port: 8101

spring:
  application:
    name: spring-cloud-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: MICRO-SERVICE-CONSUMER

management:
  endpoints:
    web:
      exposure:
        include: "*"