server:
  port: 8105

spring:
  application:
    name: springCloud-consumer-feign


eureka: 
  client: 
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
      
  instance:
    appname: consumer-feign