server:
  port: 8001
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
      
spring:
  application:
    name: springCloud-bus
  rabbitmq:
    host:
    port:
    username:
    password:

