server:
  port: 8110

spring:
  application:
    name: springCloud-consumer-feign-hystrix-wo-hystrix


eureka: 
  client: 
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
      
feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000