server:
  port: 9100
  servlet-path: /

#自定义属性
sql: mysql
profile: abc


spring:
  application:
    name: aaaa
#  cloud:
#    config:
#      uri: http://user:password123@localhost:9000/
#      profile: dev
#      label: master
#      username: user
#      password: password1232

