server:
  port: 9100
  servlet-path: /

#自定义属性
sql: mysql
profile: abc

spring:
  application:
    name: config-client
management:
  security:
    enabled: false
  cloud:
    config:
      uri: http://127.0.0.1:9000/
      profile: dev
      label: master
      username: user
#      password: password123

