spring:
  application:
    name: springCloud-gateway-zuul-filter

server:
  port: 8111
  
eureka: 
  client: 
    service-url: 
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

#通过设置这个属性可以访问这个url  http://localhost:8111/routes
management:
  security:
    enabled: false



