server:
  port: 8106

spring:
  application:
    name: spring-cloud-consumer-feign-cust
  output:
    ansi:
      enabled: always

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.andy.order: DEBUG

