server:
  port: 8106

spring:
  application:
    name: springCloud-consumer-feign-cust
  output:
    ansi:
      enabled: always

eureka:
  client: 
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
      
      
logging:
  level:
    com.jja.UserFeignClient: DEBUG

