server:
  port: 9000
spring:
  application:
      name: springCloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/thethink/config_repo
#          uri: ${user.dir}\spring-cloud-config-server\src\main\resources\configs
#D:\workspace\idea\springCloud-examples\springCloud-config-server\src\main\resources\configs


management:
  security:
    enabled: false
#encrypt:
#  key: foo
