spring:
  application:
    name: springCloud-gateway-zuul

server:
  port: 8111
  
eureka: 
  client: 
    service-url: 
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true


zuul:
  #访问网关的前缀
#  prefix: /api
  #去掉前缀默认为true
#  strip-prefix: false
logging:
  level:
    com.netflix: defug


    #通过设置这个属性可以访问这个url  http://localhost:8111/routes
management:
  security:
    enabled: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000






