spring:
  application:
    name: springCloud-gateway-zuul

server:
  port: 8111
  
eureka: 
  client: 
    service-url: 
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true


zuul:
  #访问网关的前缀
#  prefix: /api
  #去掉前缀默认为true
#  strip-prefix: false
logging:
  level:
    com.netflix: defug

    #spirngboot1.5以后需要设置这个配置来访问actor
management:
  security:
    enabled: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000






