server:
  port: 8001
  
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
#      defaultZone: http://user:password@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka

  instance:
#    ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.name}:${server.port}
    metadata-map:       #自定义元数据
      zone: ABC
      ruolin: BBC
#    lease-renewal-interval-in-seconds: 5
#    prefer-ip-address: true
#    appname: USER-SERVICE-HAHA
#    hostname: user
    #调整状态页面
    status-page-url-path: /health
    #调整将康检查的页面
#    health-check-url-path: /beans

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.description.sql.BasicBinder: TRACE
    com.andy: DEBUG
    
spring:
  application:
    name: spring-cloud-provider
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
management:
  endpoints:
    web:
      exposure:
        include: "*"